title: Matt Fong
email: matthewjf@gmail.com
description: ""
baseurl: "/"
url: "https://matthewjf.github.io"
github_username:  matthewjf
github:
  repo: "https://github.com/matthewjf/matthewjf.github.io"

# Build settings
markdown: kramdown
theme:
plugins: []
