title: Matt Fong
email: matthewjf@gmail.com
description: ""
url: "https://matthewjf.github.io"
github_username:  matthewjf
github:
  repo: "https://github.com/matthewjf/matthewjf.github.io"

# Build settings
markdown: kramdown
theme:
plugins: []

# Social
github_url: "https://github.com/matthewjf"
linkedin_url: "https://www.linkedin.com/in/mattjfong"
