# title: Matt Fong
# email: matthewjf@gmail.com
# description: ""
# url: "https://matthewjf.github.io"
# github_username:  matthewjf
# github:
#   repo: "https://github.com/matthewjf/matthewjf.github.io"

# # Build settings
# markdown: kramdown
# theme:
# plugins: []

# # Social
# github_url: "https://github.com/matthewjf"
# linkedin_url: "https://www.linkedin.com/in/mattjfong"

#-------------------------------
# General Site Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://matthewjf.github.io" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "/blog/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
  - scope:
      path: '_posts'
    values:
      permalink: /blog/:slug

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed
